#!/bin/sh
install() {
    # disable firewall
    ufw disable
    
    # update
    apt update

    # download requires
    apt install certbot nginx unzip -y
    base_url=https://github.com/XTLS/Xray-core
    version=$(curl ${base_url} | grep 'style="max-width: none' | sed -r 's|.*Xray-core (.*)<\/span>|\1|')
    download_url=$base_url/releases/download/${version}/Xray-linux-64.zip
    wget ${download_url} -O Xray-linux-64.zip
    unzip -o Xray-linux-64.zip -d ./xray
    
    # configure nginx
    systemctl enable nginx
    sed -e '/listen.*\[::\]:80/d' -re 's/80/81 http2/' -i.bak /etc/nginx/sites-available/default
    rm -rf /var/www/html/*
    echo "not" > /var/www/html/index.html
    systemctl restart nginx

    # get certificate
    read -p "sni: " sni
    certbot certonly --standalone -d ${sni}
    ca=/etc/letsencrypt/live/${sni}/fullchain.pem
    key=/etc/letsencrypt/live/${sni}/privkey.pem
    
    # add certbot daily enable
    systemctl enable certbot.timer
    
    read -p "vless id: " id
    
    # config xray
    systemctl stop xray
    \cp ./xray/xray /usr/bin/
    if [ ! -d "/etc/xray/" ];then
        mkdir /etc/xray/
    fi
	# xray configfile
    cat > /etc/xray/config.json <<-EOF
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "${id}",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "81"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "rejectUnknownSni": true,
                    "minVersion": "1.2",
                    "certificates": [
                        {
                            "ocspStapling": 3600,
                            "certificateFile": "${ca}",
                            "keyFile": "${key}"
                        }
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ],
    "policy": {
        "levels": {
            "0": {
                "handshake": 2,
                "connIdle": 120
            }
        }
    }
}
EOF
    # xray service
    cat > /etc/systemd/system/xray.service <<-EOF
[Unit]
Description=Xray Service
Documentation=https://github.com/xtls
After=network.target nss-lookup.target
[Service]
User=root
ExecStart=/usr/bin/xray run -config /etc/xray/config.json
Restart=on-failure
RestartPreventExitStatus=23
LimitNPROC=10000
LimitNOFILE=1000000
[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable xray
    systemctl restart xray
    
    # print config
    echo "sni: ${sni}"
    echo "ca: ${ca}"
    echo "key: ${key}"
    echo "vless id: ${id}"
}
install
